### ISSUE TITLE
Propuesta: "¿Qué es un contenedor? Creando un contenedor desde 0"

### ISSUE THREAD

**Issue by juanjcsr** [cloudnativemx/propuestas-meetup#1]
En el meetup pasado hubo varias preguntas sobre contenedores. Me gustaría dar una charla en donde platiquemos sobre lo que es un contenedor así como algunas herramientas de Linux que permiten que herramientas como Docker, LXC o OpenVZ existan. Todo esto mientras construimos un contenedor en pocas líneas de código, utilizando Go.

Esta plática está basada en un [blogpost](https://medium.com/problem-solvers-tech-tales/creando-un-contenedor-en-go-desde-cero-87eb6f352385) que escribí hace tiempo, basado en una charla de [Liz Rice](https://www.youtube.com/watch?v=Utf-A4rODH8). 

## Objetivo
Entender qué es un contenedor y construir uno, utilizando Go, a partir de conceptos básicos del sistema operativo (namespaces, cgroups y filesystems) 

## Outline

- ¿Qué es un contenedor?
- ¿Qué se necesita para crear un contenedor?
- Entendiendo los namespaces:  MNT, PID, UTS
- Creando el contenedor en Go.

**Comment by vaquer** [comment]
Se lee increíble @juanjcsr. ¿se necesitara llevar lap? ¿Ademas de Go se necesita otra cosa instalada? 🤘

**Comment by juanjcsr** [comment]
Más bien, pensaba llevar los ejemplos ya construidos en irlos discutiendo. Para que esto no se vuelva un taller y mejor haya tiempo de discutir cosas. Generalmente las sesiones de live coding siempre salen mal a menos que uno tenga mucha experiencia

**Comment by domix** [comment]
super bien!

tendrás chance para el 8 de mayo @juanjcsr?

**Comment by juanjcsr** [comment]
Sí @domix , el 8 de mayo está bien!

**Comment by domix** [comment]
Por favor escríbeme @juanjcsr a domingo.suarez@gmail.com para coordinarlo
