### ISSUE TITLE
Propuesta: CI/CD: otra forma de ver

### ISSUE THREAD

**Issue by says33** [cloudnativemx/propuestas-meetup#2]
Utilizando Jenkins, docker y la nube

mostrare el uso de pipeline script, sus ventajas como poder crear algo sencillo pero funcional, que nos mostrara las posibilidades que podemos alcanzar usando docker y la nube

**Comment by AgoraSecurity** [comment]
También sería interesante que nos cuenten/expliquen su experiencia de Dockers + CI
Ventajas, desventajas, hasta que punto es bueno usar dockers, donde es contraproducente, diferencias entre lenguajes (no es lo mismo CI para C++ que para Java, Python, etc.)

**Comment by domix** [comment]
Podrías para el 4 de septiembre @says33?

**Comment by says33** [comment]
@domix si amigo

**Comment by domix** [comment]
Agendado mano @says33 !, muchas gracias

**Comment by domix** [comment]
hola @says33, la fecha del meetup es el 11 de septiembre, esta bien?

**Comment by says33** [comment]
si, sin problemas

**Comment by domix** [comment]
Por favor @says33 enviame una bio tuya para hacer el anuncio de tu charla.
