### ISSUE TITLE
Chaos Engineering

### ISSUE THREAD

**Issue by Angelorum** [cloudnativemx/propuestas-meetup#7]
La idea es explicar los principios básicos de chaos engineering algunos ejemplos de su uso y reforzar la generación de sistemas distribuidos resilentes.
Mostrar con un pequeño demo de como configurar chaos monkey ó gremlins y explicar su uso.

Bueno esa es la idea, estoy documentándome para poder generar bien la presentación 
y sobre todo el Demo :P 
Si alguien tiene info que crean que sea de ayuda es más que bien recibida.

**Comment by domix** [comment]
como te queda para el 12 de marzo @Angelorum ?
